### ISSUE TITLE
image checking: check resolution instead of size

### ISSUE THREAD

**Issue by mpetris** [ADHO/dhconvalidator#31]

**Comment by christofs** [comment]
Marco, could you elaborate? Why is this a problem and what would solve it?

**Comment by mpetris** [comment]
The original goal was to check if the quality of an image is good enough for a print edition. In my implementation I got it wrong and just ensured a minimum size (width and height). But it is rather dots per inch or pixels per inch that needs to get checked, I think.

**Comment by aramiscd** [comment]
I wonder whether image quality can (and should) be checked at all.  It is always possible to scale up an image and to re-encode a low-resolution image in order to fake a higher resolution.  If somebody doesn't consider image quality a priority in the first place -- e.g. because of time pressure or because they want to include this one low resolution image, they consider very important -- then they will find ways to make their image file comply.  No malicious intent needed!  Hence it seems to me, that (1) there is no way around human eyeballs for this, and (2) the problem needs to be solved socially (e.g. by educating people about image quality).

We can still check drops per inch (dpi) though.  As far as I know, 300 dpi is a common requirement for print.  Maybe it should be even higher for scientific publications.  To compute the dpi of an image, we need to assume a fixed image size on paper.  (There is no way around this assumption.)  I would suggest full width on DIN A4 paper (210 mm × 297 mm).   Let's assume a left margin of 2.5 cm and a right margin of 2 cm.  This leaves us with an image width of 16.5 cm.  To get one pixel per drop and 300 drops per inch we need an image width of at least 1949 pixels.  So, in my Opinion Marcos implementation isn't wrong at all, since for a fixed print size dpi translates directly to pixels.  We could drop the height requirement and just set the minimum image width to 1949 px.

Maybe we should lower that to 1920 px in order to allow screenshots from full hd screens?
